apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: {{ .Release.Namespace }}
data:
  APPID: {{ tpl .Values.app.id . }}
  SERVICE_PORT: {{ .Values.hosts.servicePort | quote }}
