apiVersion: theia.cloud/v3beta
kind: AppDefinition
metadata:
  name: theia-cloud-demo
spec:
  name: theia-cloud-demo
  image: {{ .Values.image.name }}
  pullSecret: {{ .Values.image.pullSecret }}
  uid: {{ .Values.image.uid | default "101" }}
  port: 3000
  host: {{ .Values.hosts.instance }}
  ingressname: theia-cloud-demo-ws-ingress
  minInstances: 0
  maxInstances: 10
  timeout:
    limit: {{ .Values.image.timeoutLimit }}
    strategy: {{ .Values.image.timeoutStrategy }}
  requestsMemory: 1000M
  limitsMemory: 4Gi
  requestsCpu: "100m"
  limitsCpu: "4"
  downlinkLimit: 30000
  uplinkLimit: 30000
  mountPath: "/projects/"
